apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-{{ .Values.environment }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: external-secrets-store-aws-{{ .Values.environment }}-awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: external-secrets-store-aws-{{ .Values.environment }}-awssm-secret
            key: secret-access-key
